name: Build & Push to GHCR

on:
  push:
    branches: [ main ]    # mainブランチにpush時に実行
  workflow_dispatch:       # 手動実行も可能

permissions:
  contents: read
  packages: write          # GHCRにpushするために必要

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/sitemap-checker

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (optional: 将来ARMなどビルドするなら)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64
          # cache-from/to を使うと次回以降速くなります（任意）
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
