name: Run Sitemap Checker (Manual)

on:
  workflow_dispatch:
    inputs:
      sites:
        description: "1行1サイトのURL（例: https://example.com/sitemap.xml）"
        required: true
        type: string

permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/sitemap-checker

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs (debug)
        run: |
          echo "SITES:"
          printf '%s\n' "${{ github.event.inputs.sites }}"
